version: '3.7'

services:
  db_dev:
    build: db/
    volumes:
      - data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      DB_ENV: "development"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password

  api_stage:
    restart: always
    build: kono-api/
    environment:
      HOST: "dev.kono.sparcs.org"
      PORT: 4000
      DB_HOST: "db_dev"
      DB_PORT: 3306
      DB_AUTH_USER: "api"
      DB_AUTH_PASSWORD_FILE: /run/secrets/db_authorized_api_password
      DB_USER: "unauthorized_api"
      DB_PASSWORD_FILE: /run/secrets/db_unauthorized_api_password
      DB_DATABASE: "kono"
      PASSWORD_KEY_FILE: /run/secrets/api_password_key
      JWT_KEY_FILE: /run/secrets/api_jwt_key
      UPLOAD_DIR: /usr/src/assets
    volumes:
      - api_build_stage:/usr/src/app
      - api_log_stage:/usr/src/log
      - app_static_stage:/usr/src/assets
    secrets:
      - db_authorized_api_password
      - db_unauthorized_api_password
      - api_password_key
      - api_jwt_key

  nginx_stage:
    depends_on:
      - api_stage
    restart: always
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - app_build_stage:/usr/share/nginx/html
      - nginx_log_stage:/var/log/nginx
      - app_static_stage:/usr/share/nginx/assets

volumes:
  data_dev:
  api_build_stage:
  api_log_stage:
  app_build_stage:
  nginx_log_stage:
  app_static_stage:

secrets:
  db_root_password:
    file: config/dev/db_root_password
  api_password_key:
    file: config/dev/api_password_key
  api_jwt_key:
    file: config/dev/api_jwt_key
