version: '3.7'

services:
  db_production:
    build: db/
    volumes:
      - data_production:/var/lib/mysql
    environment:
      DB_ENV: "production"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_dev_password
      - db_unauthorized_api_password
      - db_authorized_api_password

  api_production:
    restart: always
    build: kono-api/
    environment:
      HOST: "kono.sparcs.org"
      PORT: 4000
      DB_HOST: "db_production"
      DB_PORT: 3306
      DB_AUTH_USER: "api"
      DB_AUTH_PASSWORD_FILE: /run/secrets/db_authorized_api_password
      DB_USER: "unauthorized_api"
      DB_PASSWORD_FILE: /run/secrets/db_unauthorized_api_password
      DB_DATABASE: "kono"
      PASSWORD_KEY_FILE: /run/secrets/api_password_key
      JWT_KEY_FILE: /run/secrets/api_jwt_key
      UPLOAD_DIR: /usr/src/assets
    volumes:
      - api_build_production:/usr/src/app
      - api_log_production:/usr/src/log
      - app_static_production:/usr/src/assets
    secrets:
      - db_authorized_api_password
      - db_unauthorized_api_password
      - api_password_key
      - api_jwt_key

  nginx_production:
    depends_on:
      - api_production
    restart: always
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - app_build_production:/usr/share/nginx/html
      - nginx_log_production:/var/log/nginx
      - app_static_production:/usr/share/nginx/assets

volumes:
  data_production:
  api_build_production:
  api_log_production:
  app_build_production:
  nginx_log_production:
  app_static_production:

secrets:
  db_root_password:
    file: config/production/db_root_password
  db_dev_password:
    file: config/production/db_dev_password
  db_unauthorized_api_password:
    file: config/production/db_unauthorized_api_password
  db_authorized_api_password:
    file: config/production/db_authorized_api_password
  api_password_key:
    file: config/production/api_password_key
  api_jwt_key:
    file: config/production/api_jwt_key
