version: '3.7'

services:
  db_production:
    build: db/
    volumes:
      - data_production_volume:/var/lib/mysql
    environment:
      DB_ENV: "production"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - db_dev_password
      - db_unauthorized_api_password
      - db_authorized_api_password

  db_dev:
    build: db/
    volumes:
      - data_dev_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      DB_ENV: "development"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - source: db_root_password_dev
        target: db_root_password

  api:
    depends_on:
      - maintainer
    restart: always
    build: kono-api/
    environment:
      HOST: "kono.sparcs.org"
      PORT: 4000
      DB_HOST: "db_production"
      DB_PORT: 3306
      DB_AUTH_USER: "api"
      DB_AUTH_PASSWORD_FILE: /run/secrets/db_authorized_api_password
      DB_USER: "unauthorized_api"
      DB_PASSWORD_FILE: /run/secrets/db_unauthorized_api_password
      DB_DATABASE: "kono"
      PASSWORD_KEY_FILE: /run/secrets/api_password_key
      JWT_KEY_FILE: /run/secrets/api_jwt_key
    volumes:
      - api_build:/usr/src/app
      - api_log:/usr/src/log
      - app_static:/usr/src/assets
    secrets:
      - db_authorized_api_password
      - db_unauthorized_api_password
      - api_password_key
      - api_jwt_key

  maintainer:
    build:
      context: .
      dockerfile: Dockerfile-maintainer
    ports:
      - "8022:22"      
    environment:
      GENERATE_SOURCEMAP: "false"
    volumes:
      - api_build:/usr/src/api/dist
      - api_log:/usr/src/log/api
      - app_build:/usr/src/app/build
      - nginx_log:/usr/src/log/nginx
    secrets:
      - db_root_password

  nginx:
    depends_on:
      - api
      - maintainer
    restart: always
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - app_build:/usr/share/nginx/html
      - nginx_log:/var/log/nginx
      - app_static:/usr/share/nginx/assets

volumes:
  data_production_volume:
  data_dev_volume:
  api_build:
  api_log:
  app_build:
  nginx_log:
  app_static:

secrets:
  db_root_password:
    file: config/production/db_root_password
  db_dev_password:
    file: config/production/db_dev_password
  db_unauthorized_api_password:
    file: config/production/db_unauthorized_api_password
  db_authorized_api_password:
    file: config/production/db_authorized_api_password
  db_root_password_dev:
    file: config/dev/db_root_password
  api_password_key:
    file: config/production/api_password_key
  api_jwt_key:
    file: config/production/api_jwt_key
