FROM node:10
MAINTAINER inhibitor <inhibitor@kaist.ac.kr>

WORKDIR /usr/src/app

RUN npm i -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE $PORT

CMD [ "npm", "run", "start:dev" ]
